import Head from "next/head";
import Image_Component from "../src/Image_Component/Image_Component";
import Introduction_Component from "../src/Introduction_Component/Introduction_Component";
import mobile from "../public/images/hero-mobile.jpg";
import desktop from "../public/images/hero-desktop.jpg";

export default function Home() {
  const text = `Hello fellow shoppers! We're currently building our new fashion store.
  Add your email below to stay up-to-date with announcements and our
  launch deals.`;

  return (
    <>
      <Head>
        <title>Frontend Mentor | Base Apparel coming soon page</title>
        <meta
          name="description"
          content="Frontend Mentor | Base Apparel coming soon page generated by create next app"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="../public/images/favicon.png"
        />
      </Head>
      <main>
        <Image_Component
          mobile_img={mobile}
          mobile_w="375"
          mobile_h="250"
          desktop_img={desktop}
          desktop_w="610"
          desktop_h="800"
        />
        <Introduction_Component introduction_text={text} />
      </main>
    </>
  );
}
